version: '3'
services:
  # ddns:
  #   build:
  #     context: .
  #     dockerfile: ./etc/Dockerfile
  #     target: hotreload
  #   volumes:
  #     - .build:/var/task
  #     - ./:/app
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  #     - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  #     - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
  #     - AWS_REGION=${AWS_DEFAULT_REGION}
  
  ddns:
    hostname: ddns
    build:
      context: .
      dockerfile: ./etc/Dockerfile
      target: servermode
    # volumes:
    #   - .build:/var/task
    ports:
      - "4000:4000"
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - _LAMBDA_SERVER_PORT=8081
      - LAMBDA_DEST_PORT=localhost:8081
