AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "DDNS (Dynamic DNS) Api for updating Route53 records"

Parameters:
  Environment:
    Type: String
    Description: "Environment"
    Default: "dev"
  Debug:
    Type: String
    Description: Debug mode for logs
    Default: "true"
    AllowedValues:
    - "true"
    - "false"
  Architecture:
    Type: String
    Description: When you need to specify a different architecture for compiling locally (See makefile build commands)
    Default: arm64
Globals:
  Function:
    Runtime: provided.al2023
    Architectures: [!Ref Architecture]
    Timeout: 30
    MemorySize: 128
    Handler: bootstrap
    Environment:
      Variables:
        SOME_ENV_VAR: "some-value"

Resources:

  ### Functions ###
  UpdateIP:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./
      Handler: bootstrap
      Events:
        RefreshIP:
          Type: Api
          Properties:
            Path: /refresh-ip
            Method: get
      # Policies:
      #   - LambdaInvokePolicy:
      #       FunctionName: '*'